[profile.default]
src = "src"
test = "tests"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
evm_version = "cancun"
optimizer = true
optimizer_runs = 10_000
bytecode_hash = "none"
cbor_metadata = false
extra_output = ["storageLayout"]

[profile.default.fuzz]
runs = 512
max_test_rejects = 65_536

[profile.default.invariant]
runs = 128
depth = 32
fail_on_revert = false

[profile.ci]
fuzz.runs = 2_048
invariant.runs = 512
invariant.depth = 64

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true
int_types = "long"
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
sort_imports = true
